name: main

on:
  pull_request:
    branches:
      - main
  push:
    branches: ['**']
  schedule:
    - cron: '0 0 * * *'
  repository_dispatch:
    types: [contentful.deploy]

jobs:
  common-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - name: Set working directory
        run: cd $GITHUB_WORKSPACE
      - name: Instalar dependências
        run: npm install

  lint:
    runs-on: ubuntu-latest
    needs: common-setup
    steps:
      - name: Executar lint
        run: npm run lint

  prettier:
    runs-on: ubuntu-latest
    needs: common-setup
    steps:
      - name: Executar prettier
        run: npm run prettier

  jest:
    runs-on: ubuntu-latest
    needs: common-setup
    steps:
      - name: Executar jest
        run: npm test

  build-deploy:
    needs:
      - jest
      - prettier
      - lint
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Executar build
        run: npm run build

      - name: Executar deploy
        run: npx netlify-cli deploy --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --prod
