name: main

on:
  pull_request:
    branches: ['**']
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  repository_dispatch:
    types: [contentful.deploy]

jobs:
  code-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1

      - name: Instalar dependências
        run: npm install

      - name: Executar lint
        run: npm run lint

      - name: Executar prettier
        run: npm run prettier

      - name: Executar jest
        run: npm test


  build-deploy:
    needs:
      - code-check
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1

      - name: Instalar dependências
        run: npm install

      - name: Executar build
        run: npm run build

      - name: Executar deploy
        run: npx netlify-cli deploy --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --prod